title: "Georges F Kanaan | DevSecOps Portfolio"
description: "Portfolio DevSecOps â€“ Kubernetes, CI/CD, Policy as Code, Cloud Security"
baseurl: "" # laisser vide pour github.io
url: "https://georgesfk.github.io"
theme: minima
markdown: kramdown
